### ISSUE TITLE
Improve sub-optimal symfony/yaml requirement

### ISSUE THREAD

**Issue by Tuurlijk** [MaxServ/t3ext-yaml-configuration#4] opened 2016-02-02 13:48 UTC
Does not play nice on TYPO3 6.2

**Comment by dev-rke** [comment] 2016-05-09 09:23
Same here, the composer require statement does not install the dependencies.
I used the package from https://composer.typo3.org/satis.html 

```
$ composer require typo3-ter/yaml-configuration
```

Some ideas?

**Comment by Tuurlijk** [comment] 2016-05-09 11:24
Well, yes. TYPO3 6.2 is not fully composer-aware. You can add the symfony/yaml requirement to your composer.json you have in your website root. That should work.

**Comment by dev-rke** [comment] 2016-05-09 20:38
Sorry, i forgot to mention i am using 7.6.6 LTS and having this trouble.
There seems something misconfigured, because the symfony/yaml dependency will not be installed.

**Comment by josefglatz** [comment] 2018-12-04 23:20
Can't reproduce this in TYPO3 9.5 LTS. For now I will close the issue, as the extension will not get an update for older TYPO3 versions. Everyone is invited to contribute

**Closed as completed by josefglatz** 2018-12-04 23:20 UTC
